### ISSUE TITLE
求虚拟主机版

### ISSUE THREAD

**Issue by zhanggaoxuan** [tonghm0808/WX_TaoBaoCoupons#1]
百度BAE现在只剩下专业版的了，一个月80+，太贵。
求虚拟主机版，或者VPS版，另外求使用教程

**Comment by tonghm0808** [comment]
虚拟主机安装python2.7环境 ，然后安装一下requirements里面的包，就可以了。最后把index.py里面的最后一句换成自己的wsgi接口的服务器框架。bae   2毛钱一天还提供免费的mongodb数据库，唉再也找不到了啊
